#git_repo: "https://github.com/burcuakkayaa/Petstore-with-Karate/tree/main/src/test/java/features"
test_folder: "D:/softwares/Java/Hackthon/KarateSpringProject/SpringBootDemo/src/test/java"
branch: "main"
#test_folder: "tests"
karate_runner: "mvn test -Dkarate.options="
redis_host: "localhost"
redis_port: 6379
redis_db: 0
