git_repo: "https://github.com/kasiperumal/payment_microservice.git"
#test_folder: "D:/softwares/Java/Hackthon/payment_microservice/src/test/java/com/payment/bdd"
branch: "main"
test_folder: "/src/test/java/com/payment/bdd"
karate_runner: "mvn test -Dkarate.options="
redis:
  host: "localhost"
  port: 6379
  db: 0
  decode_responses: true
