git_repo: "https://github.com/kasiperumal/payment_microservice.git"
#test_folder: "D:/softwares/Java/Hackthon/payment_microservice/src/test/java/com/payment/bdd"
branch: "main"
test_folder: "/src/test/java/com/payment/bdd"
karate_runner: "mvn test -Dkarate.options="
redis:
  host: redis-12854.fcrce172.us-east-1-1.ec2.redns.redis-cloud.com
  port: 12854
  username: default
  password: Y6sQhSvZsIugnBcPAo8zlavlwslWAYs1
  db: 0
  decode_responses: True
