services:
  - type: web
    name: karate-test-runner
    runtime: python
    envVars:
      - key: PORT
        value: 10000
    buildCommand: "./build.sh"
    startCommand: "python3 -m uvicorn api:app --host 0.0.0.0 --port 10000"
